---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetmicroservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnetmicroservice
    spec:
      containers:
      - name: dotnetmicroservice
        image: souravbarua/dotnetmicroservicewebapi:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: dotnetmicroservice
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetmicroservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: dotnetmicroservice